// <auto-generated />
using MenuDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuDemo.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20250927125421_UpdateImageUrls")]
    partial class UpdateImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuDemo.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.ustadonerci.com/media/products/durum-et-doner_b.png",
                            Name = "Doner Durum",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://i.nefisyemektarifleri.com/2022/05/29/orijinal-antep-usulu-patlican-kebabi-3.jpg",
                            Name = "Patlican Kebabi",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/5/55/Adana_kebab.jpg",
                            Name = "Adana Kebap",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://www.diyetkolik.com/site_media/media/foodrecipe_images/ufra-kabap.png",
                            Name = "Urfa Kebap",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://cevatusta.com.tr/wp-content/uploads/2020/11/Urfa-Lahmacun.jpg",
                            Name = "Lahmacun",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://turkishfoodie.com/wp-content/uploads/2019/01/Pide.jpg",
                            Name = "Pide",
                            Price = 11.99
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://i.lezzet.com.tr/images-xxlarge-secondary/manti-nasil-pisirilir-9853d099-517c-4e89-be1c-960b703dcb8e.jpg",
                            Name = "Manti",
                            Price = 13.99
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://www.unileverfoodsolutions.com.tr/dam/global-ufs/mcos/TURKEY/calcmenu/recipes/TR-recipes/general/k%C3%B6fte-izgara/main-header.jpg",
                            Name = "Kofte",
                            Price = 10.99
                        });
                });

            modelBuilder.Entity("MenuDemo.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 3,
                            IngredientId = 15
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 4,
                            IngredientId = 15
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 5,
                            IngredientId = 15
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 9
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 10
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 11
                        },
                        new
                        {
                            DishId = 6,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 12
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 13
                        },
                        new
                        {
                            DishId = 7,
                            IngredientId = 14
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 6
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 7
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 8
                        },
                        new
                        {
                            DishId = 8,
                            IngredientId = 15
                        });
                });

            modelBuilder.Entity("MenuDemo.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lavas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Et"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Domates"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biber"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Patlican"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kiyma"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Soğan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sarimsak"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hamur"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Peynir"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Yumurta"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Un"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Yoğurt"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tereyaği"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Baharat"
                        });
                });

            modelBuilder.Entity("MenuDemo.Models.DishIngredient", b =>
                {
                    b.HasOne("MenuDemo.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuDemo.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MenuDemo.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("MenuDemo.Models.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
